# Generated by Django 3.0.4 on 2020-05-27 15:03

import Product.models
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainClassProductNav',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('ProductTitle', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False, verbose_name='Active Status')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('ModifiedDate', models.DateTimeField(blank=True, null=True, verbose_name='Modified On')),
                ('ModifiedBy', models.CharField(blank=True, max_length=250, null=True, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'MainClassProduct List',
                'verbose_name_plural': 'MainClassProduct List',
                'db_table': 'MainClassProduct',
            },
        ),
        migrations.CreateModel(
            name='SubClassProductNav',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('ProductTitle', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False, verbose_name='Active Status')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('ModifiedDate', models.DateTimeField(blank=True, null=True, verbose_name='Modified On')),
                ('ModifiedBy', models.CharField(blank=True, max_length=250, null=True, verbose_name='Modified By')),
                ('MainProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.MainClassProductNav')),
            ],
            options={
                'verbose_name': 'SubClassProduct List',
                'verbose_name_plural': 'SubClassProduct List',
                'db_table': 'SubClassProduct',
            },
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('Is_Spl', models.BooleanField(default=False, verbose_name='Is_the_ProductSpllist')),
                ('SplList', models.CharField(choices=[('tf', 'Top-Featured'), ('bs', 'Best-Seller'), ('hd', 'Hot-Deal')], max_length=200)),
                ('Offer', models.CharField(max_length=240, verbose_name='Offer')),
                ('ProductImage', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, max_length=255, quality=100, size=[370, 350], upload_to=Product.models.update_ProductCat)),
                ('ProductTitle', models.CharField(max_length=200, verbose_name='Product Title')),
                ('StrikePrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Strike Price')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product Price')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active Status')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('ModifiedDate', models.DateTimeField(blank=True, null=True, verbose_name='Modified On')),
                ('ModifiedBy', models.CharField(blank=True, max_length=250, null=True, verbose_name='Modified By')),
                ('SubProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.SubClassProductNav')),
            ],
            options={
                'verbose_name': 'ProductDetails List',
                'verbose_name_plural': 'ProductDetails List',
                'db_table': 'ProductDetails',
            },
        ),
        migrations.CreateModel(
            name='InduvialProductReviews',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('Reviews', models.TextField(verbose_name='Descriptions')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active Status')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('ModifiedDate', models.DateTimeField(blank=True, null=True, verbose_name='Modified On')),
                ('ModifiedBy', models.CharField(blank=True, max_length=250, null=True, verbose_name='Modified By')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.ProductDetails')),
            ],
            options={
                'verbose_name': 'InduvialProductReviews List',
                'verbose_name_plural': 'InduvialProductReviews List',
                'db_table': 'InduvialProductReviews',
            },
        ),
        migrations.CreateModel(
            name='InduvialProductImages',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('ProductImage', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, max_length=255, quality=100, size=[370, 350], upload_to=Product.models.induvialProduct)),
                ('is_active', models.BooleanField(default=False, verbose_name='Active Status')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('ModifiedDate', models.DateTimeField(blank=True, null=True, verbose_name='Modified On')),
                ('ModifiedBy', models.CharField(blank=True, max_length=250, null=True, verbose_name='Modified By')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.ProductDetails')),
            ],
            options={
                'verbose_name': 'InduvialProductImages List',
                'verbose_name_plural': 'InduvialProductImages List',
                'db_table': 'InduvialProductImages',
            },
        ),
        migrations.CreateModel(
            name='InduvialProductDetails',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField(verbose_name='Descriptions')),
                ('AvalibleNo', models.IntegerField()),
                ('is_active', models.BooleanField(default=False, verbose_name='Active Status')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('ModifiedDate', models.DateTimeField(blank=True, null=True, verbose_name='Modified On')),
                ('ModifiedBy', models.CharField(blank=True, max_length=250, null=True, verbose_name='Modified By')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.ProductDetails')),
            ],
            options={
                'verbose_name': 'InduvialProductDetails List',
                'verbose_name_plural': 'InduvialProductDetails List',
                'db_table': 'InduvialProductDetails',
            },
        ),
    ]
