# Generated by Django 3.0.4 on 2020-05-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20200528_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
