# Generated by Django 3.0.4 on 2020-06-03 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0003_productdetails_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total number of product')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active Status')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('ModifiedDate', models.DateTimeField(blank=True, null=True, verbose_name='Modified On')),
                ('ModifiedBy', models.CharField(blank=True, max_length=250, null=True, verbose_name='Modified By')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.ProductDetails')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart List',
                'verbose_name_plural': 'Cart List',
                'db_table': 'Cart',
            },
        ),
    ]
