# Generated by Django 3.0.4 on 2020-05-27 15:03

import LandingPage.models
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('Heading', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=255)),
                ('Link', models.URLField()),
                ('is_active', models.BooleanField(default=False, verbose_name='Active Status')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('ModifiedDate', models.DateTimeField(blank=True, null=True, verbose_name='Modified On')),
                ('ModifiedBy', models.CharField(blank=True, max_length=250, null=True, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Banner List',
                'verbose_name_plural': 'Banner List',
                'db_table': 'Banner',
            },
        ),
        migrations.CreateModel(
            name='BoxAdModel',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('AdImage', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, max_length=255, quality=100, size=[570, 326], upload_to=LandingPage.models.update_Ads)),
                ('is_active', models.BooleanField(default=False, verbose_name='Active Status')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('ModifiedDate', models.DateTimeField(blank=True, null=True, verbose_name='Modified On')),
                ('ModifiedBy', models.CharField(blank=True, max_length=250, null=True, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'BoxAds List',
                'verbose_name_plural': 'BoxAds List',
                'db_table': 'BoxAds',
            },
        ),
        migrations.CreateModel(
            name='HeaderLinkGenerateModel',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False, verbose_name='Active Status')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('ModifiedDate', models.DateTimeField(blank=True, null=True, verbose_name='Modified On')),
                ('ModifiedBy', models.CharField(blank=True, max_length=250, null=True, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'HeaderLinkGenerate List',
                'verbose_name_plural': 'HeaderLinkGenerate List',
                'db_table': 'HeaderLinkGenerate',
            },
        ),
        migrations.CreateModel(
            name='LogoModel',
            fields=[
                ('SNo', models.AutoField(primary_key=True, serialize=False)),
                ('Logo', django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, max_length=255, quality=100, size=[180, 200], upload_to=LandingPage.models.update_Logo)),
                ('Alt', models.CharField(max_length=100)),
                ('CallUs', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False, verbose_name='Active Status')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('ModifiedDate', models.DateTimeField(blank=True, null=True, verbose_name='Modified On')),
                ('ModifiedBy', models.CharField(blank=True, max_length=250, null=True, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Logo List',
                'verbose_name_plural': 'Logo List',
                'db_table': 'Logo',
            },
        ),
        migrations.CreateModel(
            name='HomeProductCatModel',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('ProductTitle', models.CharField(max_length=255)),
                ('ProductImage', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, max_length=255, quality=100, size=[500, 500], upload_to=LandingPage.models.update_ProductCat)),
                ('is_active', models.BooleanField(default=False, verbose_name='Active Status')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('ModifiedDate', models.DateTimeField(blank=True, null=True, verbose_name='Modified On')),
                ('ModifiedBy', models.CharField(blank=True, max_length=250, null=True, verbose_name='Modified By')),
                ('SubProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.SubClassProductNav')),
            ],
            options={
                'verbose_name': 'HomeProductCat List',
                'verbose_name_plural': 'HomeProductCat List',
                'db_table': 'HomeProductCat',
            },
        ),
        migrations.CreateModel(
            name='BannerImagesModel',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('Banner', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, max_length=255, quality=100, size=[1920, 1000], upload_to=LandingPage.models.update_Banner)),
                ('is_active', models.BooleanField(default=False, verbose_name='Active Status')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('ModifiedDate', models.DateTimeField(blank=True, null=True, verbose_name='Modified On')),
                ('ModifiedBy', models.CharField(blank=True, max_length=250, null=True, verbose_name='Modified By')),
                ('HeaderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LandingPage.BannerModel')),
            ],
            options={
                'verbose_name': 'BannerImages List',
                'verbose_name_plural': 'BannerImages List',
                'db_table': 'BannerImages',
            },
        ),
    ]
