# Generated by Django 3.0.4 on 2020-05-22 05:19

import About.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('BannerImage', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, max_length=255, quality=100, size=[1920, 1001], upload_to=About.models.update_BannerImage)),
                ('Title', models.CharField(max_length=255)),
                ('Content', models.TextField()),
                ('is_active', models.BooleanField(default=False, verbose_name='Active Status')),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('ModifiedDate', models.DateTimeField(blank=True, null=True, verbose_name='Modified On')),
                ('ModifiedBy', models.CharField(blank=True, max_length=250, null=True, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'About List',
                'verbose_name_plural': 'About List',
                'db_table': 'About',
            },
        ),
    ]
